@url=http://localhost:3001/api
@json=Content-Type: application/json

###
get {{url}}/users

### 注册
post {{url}}/register
Content-Type: application/json

{
    "username": "user1",
    "password": "123456"
}

### 登录
post {{url}}/login
{{json}}

{
    "username": "user2",
    "password": "123456"
}

### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjJkMjg4ZGYwMWI4Yjg4ZDI5ZGE3YyIsImlhdCI6MTY3MjY2NDQxNH0.YbryREA7Ui86SRR9z1Wm_kDgMLr0ulUHZ6GvssOo-sI

